version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - db_data:/app/data
    environment:
      - SECRET_KEY=yugFDDixnoG

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - backend

volumes:
  db_data: